spring:
  thymeleaf:    cache: false
            
security:
  oauth2:
    client:
      messaging-client-auth-code:
        client-id: guest
        client-secret: guest
        grant-type: authorization_code
        user-authorization-uri: http://127.0.0.1:55100/oauthServer/oauth/authorize
        access-token-uri: http://127.0.0.1:55100/oauthServer/oauth/token
        scope: message.read, message.write
        pre-established-redirect-uri: http://localhost:55300/oauthClient/oauth/authorized
        use-current-uri: false
      messaging-client-client-creds:
        client-id: guest
        client-secret: guest
        grant-type: client_credentials
        access-token-uri: http://127.0.0.1:55100/oauthServer/oauth/token
        scope: message.read, message.write
      messaging-client-password:
        client-id: guest
        client-secret: guest
        grant-type: password
        access-token-uri: http://127.0.0.1:55100/oauthServer/oauth/token
        scope: message.read, message.write

messages:
  base-uri: http://localhost:55200/oauthResource/messages