spring:
  thymeleaf:    cache: false

  security:
    # 进行登录验证的用户名和密码,由用户自行输入
    user:
      name: admin
      # 123456
      password: $2a$10$vN5dYR542V03tOvLs4ep6.W8MAMBUqm2feSGxxOLZKoGKPumM.w0y

    oauth2:
      resourceserver:
        jwt:
          # 认证服务器解析token令牌的密钥地址
          jwk-set-uri: http://127.0.0.1:55100/oauthServer/oauth/token_key
      client:
        registration:
          # 本应用注册在facebook的参数
          facebook: 
            client-id: facebook_client_id
            client-secret: facebook_client_secret
          # 本应用注册在github上的参数
          github:
            client-id: github_client_id
            client-secret: github_client_secret
          guest: 
            client-id: guest
            client-secret: guest