server:
  port: 55300
  servlet:
    context-path: /oauthClient
    
spring:
  profiles:
    active: dev
  devtools:
    livereload:
      enabled: true

logging: 
  level: 
    # 指定oauth2打印日志级别
    org.springframework.security.oauth2: trace
    '[org.springframework.web]': INFO
    '[org.springframework.security]': INFO
security:
  oauth2:
    client:
      # 第三方获得认证服务器授权码code的跳转地址
      registered-redirect-uri:
      - http://example.com