version: '3.0'
services:
  # 服务名称
  mysql:
    image: mysql:5.7
    # 解决外部无法访问
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      # root密码
      MYSQL_ROOT_PASSWORD: '52LDforever'
      # 密码不能为空
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      # 默认创建数据库test
      MYSQL_DATABASE: 'test'
      # 默认创建一个test的用户,并指定密码
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '52LDforever'
    networks:
      - test_web
  # 自己单独的springboot项目
  test-web:
    hostname: localhost
    # 需要构建的Dockerfile文件
    build: ./
    ports:
      - "38000:8080"
    # web服务依赖mysql服务,要等mysql服务先启动
    depends_on:
      - mysql
    networks:
      - test_web
# 定义一个网络,让多个组件之间可以相互连通
networks:
  test_web: