spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/dream_basic?autoReconnect=true&useUnicode=true&serverTimezone=GMT&useSSL=false
      username: root
      password: 123456
      
    url: jdbc:mysql://localhost:3306/dream_basic?autoReconnect=true&useUnicode=true&serverTimezone=GMT&useSSL=false
    
mybatis:
  mapper-locations: classpath:mapper/**.xml