server: 
  port: 5530

spring:
  application:
    name: dream-study-microservice-gateway

management: 
  endpoints:
    web:
      exposure:
        #*表示暴露info,health所有端点
        include: "*"
  endpoint:
    health:
      #默认是never
      show-details: always

logging:
  level:
    '[org.springframework.boot.actuate]': trace
    '[org.springframework.security.oauth2]': trace
