server:
  port: 55557
  servlet:
    encoding:
      charset: UTF-8
      
management:
  endpoint:
    health:
      enabled: true
    mappings:
      enabled: true
  endpoints: 
    web:
      exposure:
        include: "*"
        
spring:
  rabbitmq:
    host: 192.168.0.150