server:
  port: 55557
  servlet:
    encoding:
      charset: UTF-8
      
management:
  endpoints: 
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: 192.168.0.150
  cloud:
    bus:
      trace: 
        # 打开bus追踪,在页面上可以ip:port/trace访问
        enabled: true