server:
  port: 55100
  servlet:
    context-path: /oauthServer
    
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  profiles:
    active: dev
    
logging: 
  level: 
    org.springframework.security.oauth2: trace
    com.wy.mapper: debug