server:
  port: 55100
  servlet:
    context-path: /oauthServer
    
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    
logging: 
  level: 
    # 指定oauth2打印日志级别
    org.springframework.security.oauth2: trace
security:
  oauth2:
#    resource:
#      jwk:
#        key-set-uri: http://127.0.0.1:55100/oauthServer/oauth/token_key
    client:
      # 第三方获得认证服务器授权码code的跳转地址
      registered-redirect-uri:
      - http://example.com