#feign连接超时设置      
feign: 
  hystrix:
    enabled: true
  # 集成oauth2
  oauth2:
    enabled: true
    # 启用负载均衡
    load-balanced: true
  client:
    config: 
      # 定义FeginClient的名称,default对所有有效
      default: 
        # Feign请求参数,相当于feign.Request.Options,建立链接的超时时长
        connect-timeout: 5000
        # 读取超时时长
        read-timeout: 5000
        # Feign的日志级别,相当于代码配置的feign.Logger
        logger-level: full
        # Feign的错误解析器,相当于代码配置的feign.codec.ErrorDecoder
        error-decoder:
        # Feign的重试侧脸,相当于代码配置的feign.Retryer 
        retryer:
        # Feign拦截器,相当于代码配置的feign.RequestInterceptor 
        request-interceptors:
        # 配置熔断是否处理404异常:false->不处理
        decode404: false
  # 压缩feign请求
  compression:
    request:
      enabled: true
      # 压缩的请求类型
      mime-types:
      - application/json
      - text/xml
      - application/xml
      min-request-size: 2048
      
hystrix:
  # 是否将SpringSecurity的SecurityContext从主线程中传输到HystrixCommand注解标注的方法中使用
  shareSecurityContext: true
  
# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 建立连接所用的时间,适用于网络状况正常的情况下,两端连接超时时间,默认1S
  ReadTimeout: 5000
  # 建立连接后从服务器读取到可用资源所用的超时时间,默认1S
  ConnectTimeout: 5000