server:
  port: 55200
  servlet:
    context-path: /oauthResource
    
spring:
#  profiles:
#    active: dev
  devtools:
    restart:
      enabled: true
#      trigger-file: version
    
logging: 
  level: 
    # 指定oauth2打印日志级别
    org.springframework.security.oauth2: trace
security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http:// 127.0.0.1:55100/oauthServer/oauth/token_key
    client:
      # 第三方获得认证服务器授权码code的跳转地址
      registered-redirect-uri:
      - http://example.com