# 资源服务器配置
spring:
  security:
    oauth2:
      # 资源服务器配置
      resourceserver:
        jwt:
          # Jwt中claims的iss属性,也就是jwt的签发地址,即认证服务器的指定地址
          # 资源服务器会进一步的配置,通过该地址获取公钥以解析jwt
          issuer-uri: http://127.0.0.1:8080
        opaquetoken:
          # opaque方式校验
          introspection-uri: http://127.0.0.1:8888/introspect
          client-id: 资源服务器id
          client-secret: 资源服务器密码
