spring: 
  zipkin: 
    # zipkin服务器地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 抽样百分比,默认是0.1的才输出到外部环境进行观察
      probability:  1
    
#zipkin的配置,auto-time-requests必须配置false,否则报错
management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false