spring: 
  rabbitmq: 
    host: 192.168.0.150
    # 端口,默认是5672
    port: 5672
    # 访问rabbitmq的用户名密码,默认都是guest,修改需要在rabbitmq的管理界面修改
    username: guest
    password: guest
    connection-timeout: 0
    template:
      # 默认的交换机名称
      exchange: default-exchange
      # 发送者重试机制
      retry:
        # 开启重试
        enabled: true
        # 首次重试的间隔时间,单位ms
        initial-interval: 1000
        # 最大重试次数
        max-attempts: 3
        # 重试时间间隔,单位ms
        max-interval: 10000
        # 每次重试的因子,1表示上次的1倍,2上次的2倍
        multiplier: 1.0
    listener:
      simple:
        # Ack是否手动确认,manual手动,none不确认,auto自动,默认自动
        # 若在开启手动确认消息,则必须在消费者中手动确认消息,否则生产者会不停的发消息
#        acknowledge-mode: manual
        # 消费者数量
        concurrency: 10
        max-concurrency: 10
        # 每次从队列中取出的消息数
        prefetch: 1
        # 消费失败后立刻将消息重新发送到队列中,true->是,false->否
        default-requeue-rejected: true
        retry:
          # 是否开启重试机制,默认不开启
          enabled: true
          # 最大重试次数,默认3次
          max-attempts: 5
      direct:
        # NONE:不确认消息;AUTO:自动确认消息;MANUAL:手动确认消息
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
  activemq:
    broker-url: tcp://192.168.1.146:61616
    user: admin
    password: admin
    # 最大连接池数
    pool:
      max-connections: 10
  jms: 
    # 默认目的地
    template:
      default-destination: global_destination
    listener:
      # 消费者监听消息确认机制
      acknowledge-mode: auto
      # 自动启动
      auto-startup: true
    # 配置session的缓存大小为3
    cache:
      session-cache-size: 3
  cloud:
    stream:
      bindings: 
        msgClient: 
          group: test