server: 
  port: 55561

spring:
  application:
    name: cloud-feigin
    
eureka: 
  instance:
    hostname: localhost
  client: 
    service-url:
      defaultZone: http://localhost:5500/eureka,http://localhost:5501/eureka

# actuator的info信息,必须是配置文件中以info开头的自定义信息
management: 
  endpoints:
    web: 
      exposure: 
        #*表示暴露info,health所有端点
        include: "*"
  endpoint:
    health: 
      #默认是never
      show-details: always