zuul: 
  # 若不配置前缀,则默认访问其他服务URL为网关ip:port/被访问的服务名/接口URL
  prefix: /api
  host: 
    # 请求链接超时时间,默认2000ms
    connect-timeout-millis: 60000
    # 请求访问超时时间,默认10000ms
    socket-timeout-millis: 60000
  routes:
    # 路由服务的key,不在访问的url中体现.自定义
    user: 
      # 该路由服务指向哪一个服务名
      service-id: dream-study-microservice-service
      # 网关代理路径./**表示所有层级的接口,/*表示只有一层
      path: /user/**
  ignore-local-service: true
  # 禁止以服务名访问,即禁止默认的访问方式.*表示所有,也可以写多个服务名
  ignored-services: "*"
  # 禁止匹配某些URL
  ignored-patterns: /**/feign/**
  # 禁用指定过滤器:过滤器的类名,过滤器的类型
  SendErrorFilter:
    error: 
      disable: true