spring:
  thymeleaf:    cache: false
            
config:
  oauth2-client-code:    client-id: guest
    client-secret: guest    scope: message.read, message.write
    access-token-uri: http://127.0.0.1:55100/oauthServer/oauth/token
    user-authorization-uri: http://127.0.0.1:55100/oauthServer/oauth/authorize
    pre-established-redirect-uri: http://localhost:55300/oauthClient/oauth/authorized
    use-current-uri: false
  oauth2-client-credentials:    client-id: guest
    client-secret: guest
    scope: message.read, message.write
    access-token-uri: http://127.0.0.1:55100/oauthServer/oauth/token
  oauth2-client-password:    client-id: guest
    client-secret: guest
    scope: message.read, message.write
    access-token-uri: http://127.0.0.1:55100/oauthServer/oauth/token
  oauth2-client-implicit:    client-id: guest
    client-secret: guest
    scope: message.read, message.write
    access-token-uri: http://127.0.0.1:55100/oauthServer/oauth/token