spring:
  application:
    name: dream-study-microservice-server
  profiles:
    active: dev
server: 
  port: 55555
  max-http-header-size: 10000000

eureka:
  instance:
    hostname: localhost
    # 当多长时间没有收到心跳包的信息时,从注册中心中剔除本服务,默认90S
    #lease-expiration-duration-in-seconds: 30
    # 每隔10向注册中心发送心跳包,表明自己还没有宕机,默认30S
    #lease-renewal-interval-in-seconds: 10
    # 健康检查的页面
    #status-page-url-path: ${management.context-path}/info
    #health-check-url-path: ${management.context-path}/health
    # 使用域名时候的检查页面
    #status-page-url: https://${euraka.hostname}/info
    #health-check-url: https://${euraka.hostname}/health
    #home-page-url: https://${euraka.hostname}
    # eureka可以理解的元数据,不会影响客户端行为
    metadata-map:
      id: 1
  server: 
    # 清理已经停止的服务的时间间隔,默认是60秒
    eviction-interval-timer-in-ms: 60000
    # 是否开启自我保护模式,当15分钟内收到的心跳数少于一定比例的时候开启,默认是开启的
    enable-self-preservation: true
    # 15分钟内应该收到的心跳数比例,若少于这个比例,将开启自我保护模式,不删除注册信息,默认是0.85
    renewal-percent-threshold: 0.8
  client: 
    # false表示不注册到其他server上,true表示是一个客户端,若是正式环境可开启多个服务,相互注册
    register-with-eureka: false
    # true表示从其他server上获取信息,若开启集群,可注册到其他服务上
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 健康检查,只能写在application.yml中,不能写在bootstrap中
    healthcheck:
      enabled: true
    # 是否允许重定向
    #allow-redirects: false

# 开启secutiry验证,此时注册到eureka注册中心的微服务都要带上用户名和密码
#security: 
#  basic: 
#    enabled: true
#  user: 
#    name: user
#    password: 123455
    
# actuator的info信息,必须是配置文件中以info开头的自定义信息
management: 
  endpoints:
    web: 
      exposure: 
        #*表示暴露info,health所有端点
        include: "*"
  endpoint:
    health: 
      #默认是never
      show-details: always